multi_choice_format: |
  {question}

  Answer with the option's letter from the given choices and put the letter in one "\\boxed{{}}".

Strategy_Instruction:
  CoT: "Please solve the problem step by step."
  Directly: "Please ensure that your output only contains the final answer without any additional content (such as intermediate reasoning steps)."
